services:
  postgres:
    image: postgres:16
    container_name: anime_db
    restart: always
    environment:
      POSTGRES_USER: alpha
      POSTGRES_PASSWORD: jack2312
      POSTGRES_DB: evodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
